(defpackage bits-calc
  (:use #:cl)
  (:nicknames #:bits)
  (:export #:get-lsb #:popcount))

(in-package #:bits-calc)

(deftype uint32 () '(unsigned-byte 32))
(deftype uint8 () '(unsigned-byte 8))

(defmacro with-type-wrap ((op type) &body body)
  `(progn
     ,@(mapcar (lambda (form)
                 (if (and (consp form)
                          (eq (first form)
                              op))
                     `(,op ,@(mapcar (lambda (elem)
                                         `(the ,type ,elem))
                                     (rest form)))
                     form))
               body)))

(declaim (ftype (function (uint32) uint8) get-lsb))
(defun get-lsb (value)
  (declare (uint32 value))
  (macrolet ((%proc (hex)
               (let ((next? (gensym)))
                 `(with-type-wrap (logand setf)
                    (with-type-wrap (setf uint32)
                      (let ((,next? (logand value ,hex)))
                        (unless (zerop ,next?)
                          (setf value ,next?))))))))
    (%proc #xffff0000)
    (%proc #xff00ff00)
    (%proc #xf0f0f0f0)
    (%proc #xcccccccc)
    (%proc #xaaaaaaaa)
    value))

(declaim (inline popcount))
(defun popcount (value)
  (declare (uint32 value))
  (macrolet ((%proc (&rest args)
               `(with-type-wrap (+ uint32)
                  (with-type-wrap (logand uint32)
                    (with-type-wrap (ash uint32)
                      (with-type-wrap (setf uint32)
                        ,@(loop for (hex1 hex2 shift) in args
                                collect `(setf value
                                               (+ (logand value
                                                          ,hex1)
                                                  (ash (logand value
                                                               ,hex2)
                                                       ,(- shift)))))))))))
    (%proc (#x55555555 #xaaaaaaaa 1)
           (#x33333333 #xcccccccc 2)
           (#x0f0f0f0f #xf0f0f0f0 4)
           (#x00ff00ff #xff00ff00 8)
           (#x0000ffff #xffff0000 16))
    value))
